using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.Entities.Items
{
    public class ResponseItem
    {
        public List<Item> value { get; set; }
    }
    public partial class Item
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public object ForeignName { get; set; }
        public long? ItemsGroupCode { get; set; }
        public long? CustomsGroupCode { get; set; }
        public object SalesVatGroup { get; set; }
        public string BarCode { get; set; }
        public string VatLiable { get; set; }
        public string PurchaseItem { get; set; }
        public string SalesItem { get; set; }
        public string InventoryItem { get; set; }
        public object IncomeAccount { get; set; }
        public object ExemptIncomeAccount { get; set; }
        public object ExpanseAccount { get; set; }
        public string Mainsupplier { get; set; }
        public object SupplierCatalogNo { get; set; }
        public long? DesiredInventory { get; set; }
        public long? MinInventory { get; set; }
        public object Picture { get; set; }
        public object UserText { get; set; }
        public object SerialNum { get; set; }
        public long? CommissionPercent { get; set; }
        public long? CommissionSum { get; set; }
        public long? CommissionGroup { get; set; }
        public string TreeType { get; set; }
        public string AssetItem { get; set; }
        public object DataExportCode { get; set; }
        public long? Manufacturer { get; set; }
        public long? QuantityOnStock { get; set; }
        public long? QuantityOrderedFromVendors { get; set; }
        public long? QuantityOrderedByCustomers { get; set; }
        public string ManageSerialNumbers { get; set; }
        public string ManageBatchNumbers { get; set; }
        public string Valid { get; set; }
        public object ValidFrom { get; set; }
        public object ValidTo { get; set; }
        public object ValidRemarks { get; set; }
        public string Frozen { get; set; }
        public object FrozenFrom { get; set; }
        public object FrozenTo { get; set; }
        public object FrozenRemarks { get; set; }
        public string SalesUnit { get; set; }
        public long? SalesItemsPerUnit { get; set; }
        public object SalesPackagingUnit { get; set; }
        public long? SalesQtyPerPackUnit { get; set; }
        public long? SalesUnitLength { get; set; }
        public object SalesLengthUnit { get; set; }
        public long? SalesUnitWidth { get; set; }
        public object SalesWidthUnit { get; set; }
        public long? SalesUnitHeight { get; set; }
        public object SalesHeightUnit { get; set; }
        public long? SalesUnitVolume { get; set; }
        public long? SalesVolumeUnit { get; set; }
        public long? SalesUnitWeight { get; set; }
        public object SalesWeightUnit { get; set; }
        public string PurchaseUnit { get; set; }
        public long? PurchaseItemsPerUnit { get; set; }
        public object PurchasePackagingUnit { get; set; }
        public long? PurchaseQtyPerPackUnit { get; set; }
        public long? PurchaseUnitLength { get; set; }
        public object PurchaseLengthUnit { get; set; }
        public long? PurchaseUnitWidth { get; set; }
        public object PurchaseWidthUnit { get; set; }
        public long? PurchaseUnitHeight { get; set; }
        public object PurchaseHeightUnit { get; set; }
        public long? PurchaseUnitVolume { get; set; }
        public long? PurchaseVolumeUnit { get; set; }
        public long? PurchaseUnitWeight { get; set; }
        public object PurchaseWeightUnit { get; set; }
        public object PurchaseVatGroup { get; set; }
        public long? SalesFactor1 { get; set; }
        public long? SalesFactor2 { get; set; }
        public long? SalesFactor3 { get; set; }
        public long? SalesFactor4 { get; set; }
        public long? PurchaseFactor1 { get; set; }
        public long? PurchaseFactor2 { get; set; }
        public long? PurchaseFactor3 { get; set; }
        public long? PurchaseFactor4 { get; set; }
        public long? MovingAveragePrice { get; set; }
        public object ForeignRevenuesAccount { get; set; }
        public object EcRevenuesAccount { get; set; }
        public object ForeignExpensesAccount { get; set; }
        public object EcExpensesAccount { get; set; }
        public long? AvgStdPrice { get; set; }
        public object DefaultWarehouse { get; set; }
        public long? ShipType { get; set; }
        public string GlMethod { get; set; }
        public string TaxType { get; set; }
        public long? MaxInventory { get; set; }
        public string ManageStockByWarehouse { get; set; }
        public object PurchaseHeightUnit1 { get; set; }
        public long? PurchaseUnitHeight1 { get; set; }
        public object PurchaseLengthUnit1 { get; set; }
        public long? PurchaseUnitLength1 { get; set; }
        public object PurchaseWeightUnit1 { get; set; }
        public long? PurchaseUnitWeight1 { get; set; }
        public object PurchaseWidthUnit1 { get; set; }
        public long? PurchaseUnitWidth1 { get; set; }
        public object SalesHeightUnit1 { get; set; }
        public long? SalesUnitHeight1 { get; set; }
        public object SalesLengthUnit1 { get; set; }
        public long? SalesUnitLength1 { get; set; }
        public object SalesWeightUnit1 { get; set; }
        public long? SalesUnitWeight1 { get; set; }
        public object SalesWidthUnit1 { get; set; }
        public long? SalesUnitWidth1 { get; set; }
        public string ForceSelectionOfSerialNumber { get; set; }
        public string ManageSerialNumbersOnReleaseOnly { get; set; }
        public string WtLiable { get; set; }
        public string CostAccountingMethod { get; set; }
        public object Sww { get; set; }
        public object WarrantyTemplate { get; set; }
        public string IndirectTax { get; set; }
        public object ArTaxCode { get; set; }
        public object ApTaxCode { get; set; }
        public object BaseUnitName { get; set; }
        public object ItemCountryOrg { get; set; }
        public string IssueMethod { get; set; }
        public string SriAndBatchManageMethod { get; set; }
        public string IsPhantom { get; set; }
        public string InventoryUom { get; set; }
        public string PlanningSystem { get; set; }
        public string ProcurementMethod { get; set; }
        public string ComponentWarehouse { get; set; }
        public object OrderIntervals { get; set; }
        public long? OrderMultiple { get; set; }
        public object LeadTime { get; set; }
        public long? MinOrderQuantity { get; set; }
        public string ItemType { get; set; }
        public string ItemClass { get; set; }
        public long? OutgoingServiceCode { get; set; }
        public long? IncomingServiceCode { get; set; }
        public long? ServiceGroup { get; set; }
        public long? NcmCode { get; set; }
        public string MaterialType { get; set; }
        public long? MaterialGroup { get; set; }
        public long? ProductSource { get; set; }
        public string Properties1 { get; set; }
        public string Properties2 { get; set; }
        public string Properties3 { get; set; }
        public string Properties4 { get; set; }
        public string Properties5 { get; set; }
        public string Properties6 { get; set; }
        public string Properties7 { get; set; }
        public string Properties8 { get; set; }
        public string Properties9 { get; set; }
        public string Properties10 { get; set; }
        public string Properties11 { get; set; }
        public string Properties12 { get; set; }
        public string Properties13 { get; set; }
        public string Properties14 { get; set; }
        public string Properties15 { get; set; }
        public string Properties16 { get; set; }
        public string Properties17 { get; set; }
        public string Properties18 { get; set; }
        public string Properties19 { get; set; }
        public string Properties20 { get; set; }
        public string Properties21 { get; set; }
        public string Properties22 { get; set; }
        public string Properties23 { get; set; }
        public string Properties24 { get; set; }
        public string Properties25 { get; set; }
        public string Properties26 { get; set; }
        public string Properties27 { get; set; }
        public string Properties28 { get; set; }
        public string Properties29 { get; set; }
        public string Properties30 { get; set; }
        public string Properties31 { get; set; }
        public string Properties32 { get; set; }
        public string Properties33 { get; set; }
        public string Properties34 { get; set; }
        public string Properties35 { get; set; }
        public string Properties36 { get; set; }
        public string Properties37 { get; set; }
        public string Properties38 { get; set; }
        public string Properties39 { get; set; }
        public string Properties40 { get; set; }
        public string Properties41 { get; set; }
        public string Properties42 { get; set; }
        public string Properties43 { get; set; }
        public string Properties44 { get; set; }
        public string Properties45 { get; set; }
        public string Properties46 { get; set; }
        public string Properties47 { get; set; }
        public string Properties48 { get; set; }
        public string Properties49 { get; set; }
        public string Properties50 { get; set; }
        public string Properties51 { get; set; }
        public string Properties52 { get; set; }
        public string Properties53 { get; set; }
        public string Properties54 { get; set; }
        public string Properties55 { get; set; }
        public string Properties56 { get; set; }
        public string Properties57 { get; set; }
        public string Properties58 { get; set; }
        public string Properties59 { get; set; }
        public string Properties60 { get; set; }
        public string Properties61 { get; set; }
        public string Properties62 { get; set; }
        public string Properties63 { get; set; }
        public string Properties64 { get; set; }
        public string AutoCreateSerialNumbersOnRelease { get; set; }
        public long? DnfEntry { get; set; }
        public object GtsItemSpec { get; set; }
        public object GtsItemTaxCategory { get; set; }
        public long? FuelId { get; set; }
        public object BeverageTableCode { get; set; }
        public object BeverageGroupCode { get; set; }
        public long? BeverageCommercialBrandCode { get; set; }
        public long? Series { get; set; }
        public object ToleranceDays { get; set; }
        public string TypeOfAdvancedRules { get; set; }
        public string IssuePrimarilyBy { get; set; }
        public string NoDiscounts { get; set; }
        public string AssetClass { get; set; }
        public string AssetGroup { get; set; }
        public string InventoryNumber { get; set; }
        public object Technician { get; set; }
        public object Employee { get; set; }
        public object Location { get; set; }
        public string AssetStatus { get; set; }
        public object CapitalizationDate { get; set; }
        public string StatisticalAsset { get; set; }
        public string Cession { get; set; }
        public string DeactivateAfterUsefulLife { get; set; }
        public string ManageByQuantity { get; set; }
        public long? UoMGroupEntry { get; set; }
        public long? InventoryUoMEntry { get; set; }
        public object DefaultSalesUoMEntry { get; set; }
        public object DefaultPurchasingUoMEntry { get; set; }
        public object DepreciationGroup { get; set; }
        public string AssetSerialNumber { get; set; }
        public long? InventoryWeight { get; set; }
        public object InventoryWeightUnit { get; set; }
        public long? InventoryWeight1 { get; set; }
        public object InventoryWeightUnit1 { get; set; }
        public object DefaultCountingUnit { get; set; }
        public long? CountingItemsPerUnit { get; set; }
        public object DefaultCountingUoMEntry { get; set; }
        public string Excisable { get; set; }
        public long? ChapterId { get; set; }
        public object ScsCode { get; set; }
        public object SpProdType { get; set; }
        public long? ProdStdCost { get; set; }
        public string InCostRollup { get; set; }
        public string VirtualAssetItem { get; set; }
        public string EnforceAssetSerialNumbers { get; set; }
        public object AttachmentEntry { get; set; }
        public object LinkedResource { get; set; }
        public DateTimeOffset? UpdateDate { get; set; }
        public DateTimeOffset? UpdateTime { get; set; }
        public string GstRelevnt { get; set; }
        public long? SacEntry { get; set; }
        public string GstTaxCategory { get; set; }
        public long? ServiceCategoryEntry { get; set; }
        public long? CapitalGoodsOnHoldPercent { get; set; }
        public long? CapitalGoodsOnHoldLimit { get; set; }
        public long? AssessableValue { get; set; }
        public long? AssVal4Wtr { get; set; }
        public string SoiExcisable { get; set; }
        public object Tnved { get; set; }
        public string ImportedItem { get; set; }
        public long? PricingUnit { get; set; }
        public DateTimeOffset? CreateDate { get; set; }
        public DateTimeOffset? CreateTime { get; set; }
        public object NveCode { get; set; }
        public long? CtrSealQty { get; set; }
        public long? CestCode { get; set; }
        public object LegalText { get; set; }
        public long? DataVersion { get; set; }
        public object CreateQrCodeFrom { get; set; }
        public string TraceableItem { get; set; }
        public object CommodityClassification { get; set; }
        public long? WeightOfRecycledPlastic { get; set; }
        public object PlasticPackageTaxCategory { get; set; }
        public object PlasticPackageExemptionReasonForPurchase { get; set; }
        public object PlasticPackageExemptionReasonForProduction { get; set; }
        public string ULbRegistrarIt { get; set; }
        public object ULbaAjdebe { get; set; }
        public object ULbaAjhaber { get; set; }
        public string ULbaAjuufv { get; set; }
        public long? UType { get; set; }
        public object UBusinessUnitId { get; set; }
        public long? UFormaFarmac { get; set; }
        public object USubgrupo { get; set; }
        public string UPermisoimp { get; set; }
        public long? UControlStatus { get; set; }
        public long? UNumberDayControl { get; set; }
        public long? USaleQuantityCi { get; set; }
        public object UR1Rubro { get; set; }
        public string UCtrlcalidad { get; set; }
        public object UBUnimed { get; set; }
        public object UCode { get; set; }
        public object UCodactive { get; set; }
        public object UArea { get; set; }
        public object UPorcentajevariacion { get; set; }
        public long? UPorctprod { get; set; }
        public object USo101Excluircom { get; set; }
        public object UCantMaxComp { get; set; }
        public object UDiasProxVent { get; set; }
        public object UUsoSustancia { get; set; }
        public long? UCantMaxCompAcumCliExcepcional { get; set; }
        public long? UCantMaxCompAcumCli { get; set; }
        public object UActvEc { get; set; }
        public object UProSin { get; set; }
        public object UCodNandi { get; set; }
        public object UGsUm { get; set; }
        public object UCodActivo { get; set; }
        public long? UCalculoPrecio2 { get; set; }
        public long? UPorcentajeDeCobertura { get; set; }
        public string UProduce { get; set; }
        public object ULinea { get; set; }
        public object UWeb { get; set; }
        public string UWebSync { get; set; }
        public object UWebC1 { get; set; }
        public object UWebC2 { get; set; }
        public List<ItemPrice> ItemPrices { get; set; }
        public List<ItemWarehouseInfoCollection> ItemWarehouseInfoCollection { get; set; }
        public List<ItemPreferredVendor> ItemPreferredVendors { get; set; }
        public List<object> ItemLocalizationInfos { get; set; }
        public List<object> ItemProjects { get; set; }
        public List<object> ItemDistributionRules { get; set; }
        public List<object> ItemAttributeGroups { get; set; }
        public List<object> ItemDepreciationParameters { get; set; }
        public List<object> ItemPeriodControls { get; set; }
        public List<object> ItemUnitOfMeasurementCollection { get; set; }
        public List<ItemBarCodeCollection> ItemBarCodeCollection { get; set; }
        public ItemIntrastatExtension ItemIntrastatExtension { get; set; }
    }

    public partial class ItemBarCodeCollection
    {
        public long? AbsEntry { get; set; }
        public long? UoMEntry { get; set; }
        public string Barcode { get; set; }
        public object FreeText { get; set; }
    }

    public partial class ItemIntrastatExtension
    {
        public string ItemCode { get; set; }
        public object CommodityCode { get; set; }
        public object SupplementaryUnit { get; set; }
        public long? FactorOfSupplementaryUnit { get; set; }
        public object ImportRegionState { get; set; }
        public object ExportRegionState { get; set; }
        public object ImportNatureOfTransaction { get; set; }
        public object ExportNatureOfTransaction { get; set; }
        public object ImportStatisticalProcedure { get; set; }
        public object ExportStatisticalProcedure { get; set; }
        public object CountryOfOrigin { get; set; }
        public object ServiceCode { get; set; }
        public string Type { get; set; }
        public string ServiceSupplyMethod { get; set; }
        public string ServicePaymentMethod { get; set; }
        public string ImportRegionCountry { get; set; }
        public string ExportRegionCountry { get; set; }
        public object StatisticalCode { get; set; }
    }

    public partial class ItemPreferredVendor
    {
        public string BpCode { get; set; }
    }

    public partial class ItemPrice
    {
        public long? PriceList { get; set; }
        public object Price { get; set; }
        public object Currency { get; set; }
        public object AdditionalPrice1 { get; set; }
        public object AdditionalCurrency1 { get; set; }
        public object AdditionalPrice2 { get; set; }
        public object AdditionalCurrency2 { get; set; }
        public long? BasePriceList { get; set; }
        public double? Factor { get; set; }
        public List<object> UoMPrices { get; set; }
    }

    public partial class ItemWarehouseInfoCollection
    {
        public long? MinimalStock { get; set; }
        public long? MaximalStock { get; set; }
        public long? MinimalOrder { get; set; }
        public long? StandardAveragePrice { get; set; }
        public string Locked { get; set; }
        public object InventoryAccount { get; set; }
        public object CostAccount { get; set; }
        public object TransferAccount { get; set; }
        public object RevenuesAccount { get; set; }
        public object VarienceAccount { get; set; }
        public object DecreasingAccount { get; set; }
        public object IncreasingAccount { get; set; }
        public object ReturningAccount { get; set; }
        public object ExpensesAccount { get; set; }
        public object EuRevenuesAccount { get; set; }
        public object EuExpensesAccount { get; set; }
        public object ForeignRevenueAcc { get; set; }
        public object ForeignExpensAcc { get; set; }
        public object ExemptIncomeAcc { get; set; }
        public object PriceDifferenceAcc { get; set; }
        public string WarehouseCode { get; set; }
        public long? InStock { get; set; }
        public long? Committed { get; set; }
        public long? Ordered { get; set; }
        public long? CountedQuantity { get; set; }
        public string WasCounted { get; set; }
        public long? UserSignature { get; set; }
        public long? Counted { get; set; }
        public object ExpenseClearingAct { get; set; }
        public object PurchaseCreditAcc { get; set; }
        public object EuPurchaseCreditAcc { get; set; }
        public object ForeignPurchaseCreditAcc { get; set; }
        public object SalesCreditAcc { get; set; }
        public object SalesCreditEuAcc { get; set; }
        public object ExemptedCredits { get; set; }
        public object SalesCreditForeignAcc { get; set; }
        public object ExpenseOffsettingAccount { get; set; }
        public object WipAccount { get; set; }
        public object ExchangeRateDifferencesAcct { get; set; }
        public object GoodsClearingAcct { get; set; }
        public object NegativeInventoryAdjustmentAccount { get; set; }
        public object CostInflationOffsetAccount { get; set; }
        public object GlDecreaseAcct { get; set; }
        public object GlIncreaseAcct { get; set; }
        public object PaReturnAcct { get; set; }
        public object PurchaseAcct { get; set; }
        public object PurchaseOffsetAcct { get; set; }
        public object ShippedGoodsAccount { get; set; }
        public object StockInflationOffsetAccount { get; set; }
        public object StockInflationAdjustAccount { get; set; }
        public object VatInRevenueAccount { get; set; }
        public object WipVarianceAccount { get; set; }
        public object CostInflationAccount { get; set; }
        public object WhIncomingCenvatAccount { get; set; }
        public object WhOutgoingCenvatAccount { get; set; }
        public object StockInTransitAccount { get; set; }
        public object WipOffsetProfitAndLossAccount { get; set; }
        public object InventoryOffsetProfitAndLossAccount { get; set; }
        public object DefaultBin { get; set; }
        public string DefaultBinEnforced { get; set; }
        public object PurchaseBalanceAccount { get; set; }
        public string ItemCode { get; set; }
        public string IndEscala { get; set; }
        public object CnjpMan { get; set; }
        public object USo101Diassurtido { get; set; }
        public object USo101Almacencom { get; set; }
        public List<object> ItemCycleCounts { get; set; }
    }
}
